# Configuración de base de datos SQLite
db.path=jdbc:sqlite:data-generator.db

# Configuración de salida de archivos CSV
csv.output.path=output/

# Configuración de correo electrónico
mail.enabled=true
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=ximeloch9@gmail.com
mail.password=qpse anjh lbgp fwzo
